import ijson
import json

# This file parses through the wikipediapages.json file generated by parsefiles.py
# and counts up the number of incoming and outgoing links of every page.
# this is used by another file to trim down the size of wikipages.json to be usable for searching.

pages_file = "wikipages.json"

link_count_dict = {}
current_page = ""
current_subsection = ""
outgoingCount = 0
incomingCount = 0
for prefix, the_type, value in ijson.parse(open(pages_file)):
    if prefix == "" and the_type == "map_key":
        if incomingCount > 0 and outgoingCount > 0 and "list_of" not in current_page.lower():
            link_count_dict[current_page] = {"incoming": incomingCount, "outgoing": outgoingCount}
        outgoingCount = 0
        incomingCount = 0
        current_page = value
    if prefix != "" and the_type == "map_key":
        current_subsection = value
    if prefix != "" and the_type == "string":
        if current_subsection == "incoming":
            incomingCount += 1
        else:
            outgoingCount += 1

with open("linkcounts.json", "w") as json_file:
    json.dump(link_count_dict, json_file)