import ijson
import json
import itertools
import time

# This file uses the json files generated by parsefiles.py and enumerate_links.py to keep only the Wikipedia
# pages that have the most incoming or outgoing links for each page. This will make running the pathfinding algorithm
# much faster.

pages_file = "wikipages.json"
link_count_file = "linkcounts.json"
num_links = 20

link_counts = None
with open(link_count_file, "r", encoding="utf-8") as file:
    link_counts = json.load(file)

shrunk_wikipages = {}
current_page = ""
current_subsection = ""
incoming_dict = {}
outgoing_dict = {}
start_time = time.perf_counter()
for prefix, the_type, value in ijson.parse(open(pages_file)):
    if prefix == "" and the_type == "map_key":
        if len(incoming_dict) > 0 and len(outgoing_dict) > 0 and "list_of" not in current_page.lower() and current_page != "":
            sorted_in = dict(sorted(incoming_dict.items(), key=lambda item: item[1], reverse=True))
            sorted_out = dict(sorted(outgoing_dict.items(), key=lambda item: item[1], reverse=True))
            sliced_in = dict(itertools.islice(sorted_in.items(), num_links))
            sliced_out = dict(itertools.islice(sorted_out.items(), num_links))
            shrunk_wikipages[current_page] = {"incoming": sliced_in, "outgoing": sliced_out}
        current_page = value
        if current_page not in link_counts:
            current_page = ""
        incoming_dict = {}
        outgoing_dict = {}
    if prefix != "" and the_type == "map_key":
        current_subsection = value
    if prefix != "" and the_type == "string" and current_page != "":
        if current_subsection == "incoming" and value in link_counts:
            num_incoming = link_counts[value]['incoming']
            incoming_dict[value] = num_incoming
        elif value in link_counts:
            num_outgoing = link_counts[value]['outgoing']
            outgoing_dict[value] = num_outgoing

end_time = time.perf_counter()
print(f"Finished shrinking wikipages in {((end_time - start_time) / (60 * 60)):.4f} hours")

with open("wikipages_mini.json", "w") as json_file:
    json.dump(shrunk_wikipages, json_file)
        